### ISSUE TITLE
When the host doesn't have openssl...

### ISSUE THREAD

**Issue by daveloyall** [vbezhenar/shenc#1]
When the host doesn't have openssl, embed a statically linked copy of it in the script?

Bonus points for making it work on multiple architectures.  (It's a shell script, so...)

Anyway, thanks for your work, @vbezhenar.  Now we can all act like fictitious movie hackers. :)

**Comment by vbezhenar** [comment]
I want it to be cross-platform and a statically linked copy means that it'll work only with Linux (or whatever system that binary was compiled for, including specific architecture). Also it's one thing to run not so big script and another thing to run some unknown binary which happens to be named openssl. Who knows what it really is?

OS X includes copy of openssl in the base system. Many Linux distributions and some BSD systems too. So I don't think it has many use-cases. User always can do "apt-get install openssl" or something similar and it's much better than running binary from the script.

For such a system it would be better to create a completely different program which will generate small statically linked binary file with necessary algorithm implementations included (RSA, AES do not require that much code) so it won't depend on anything at all (except operating system and architecture, of course).

Thanks for your kind words, I appreciate it. I hope, this project is useful.
